context:
  name: conftest
  version: "0.65.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/open-policy-agent/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 2de0a7a7834b1b6d8861dbb7508a1bf9421ab1045dca180457a729582bf9b922
  target_directory: src

build:
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses --ignore github.com/open-policy-agent/conftest
    - if: unix
      then: go build -v -o $PREFIX/bin/conftest -ldflags="-s -w"
      else: go build -v -o %LIBRARY_BIN%\conftest.exe -ldflags="-s"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script: conftest --help
  - package_contents:
      bin:
        - conftest
      strict: true

about:
  homepage: https://github.com/open-policy-agent/conftest
  summary: Write tests against structured configuration data using the Open Policy Agent Rego query language
  description: |
    Conftest helps you write tests against structured configuration data. Using Conftest you can write tests for your Kubernetes configuration, Tekton pipeline definitions, Terraform code, Serverless configs or any other config files.

    Conftest uses the Rego language from Open Policy Agent for writing the assertions. You can read more about Rego in How do I write policies in the Open Policy Agent documentation.
  license: Apache-2.0
  license_file:
    - src/LICENSE
    - library_licenses/
  documentation: https://conftest.dev
  repository: https://github.com/open-policy-agent/conftest

extra:
  recipe-maintainers:
    - xhochy
